"""empty message

Revision ID: 19275adc3af8
Revises: ec8b33d8211e
Create Date: 2022-04-04 22:54:55.571065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19275adc3af8'
down_revision = 'ec8b33d8211e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_status',
    sa.Column('approval_status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('approval_status_id')
    )
    op.create_index(op.f('ix_approval_status_created_date'), 'approval_status', ['created_date'], unique=False)
    op.create_index(op.f('ix_approval_status_deleted_date'), 'approval_status', ['deleted_date'], unique=False)
    op.create_index(op.f('ix_approval_status_updated_date'), 'approval_status', ['updated_date'], unique=False)
    op.create_table('leave_type',
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('days_per_year', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('leave_type_id')
    )
    op.create_index(op.f('ix_leave_type_created_date'), 'leave_type', ['created_date'], unique=False)
    op.create_index(op.f('ix_leave_type_deleted_date'), 'leave_type', ['deleted_date'], unique=False)
    op.create_index(op.f('ix_leave_type_updated_date'), 'leave_type', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_type_updated_date'), table_name='leave_type')
    op.drop_index(op.f('ix_leave_type_deleted_date'), table_name='leave_type')
    op.drop_index(op.f('ix_leave_type_created_date'), table_name='leave_type')
    op.drop_table('leave_type')
    op.drop_index(op.f('ix_approval_status_updated_date'), table_name='approval_status')
    op.drop_index(op.f('ix_approval_status_deleted_date'), table_name='approval_status')
    op.drop_index(op.f('ix_approval_status_created_date'), table_name='approval_status')
    op.drop_table('approval_status')
    # ### end Alembic commands ###
