"""change column names

Revision ID: 5ae17e659c8b
Revises: bc8f3523135e
Create Date: 2022-04-26 12:28:31.468725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae17e659c8b'
down_revision = 'bc8f3523135e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_is_admin', sa.Boolean(), nullable=False))
    op.add_column('employee', sa.Column('employee_is_manager', sa.Boolean(), nullable=False))
    op.drop_column('employee', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    op.drop_column('employee', 'employee_is_manager')
    op.drop_column('employee', 'employee_is_admin')
    # ### end Alembic commands ###
