"""change column names

Revision ID: bc8f3523135e
Revises: f0f0ca9029a7
Create Date: 2022-04-26 12:27:22.147589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8f3523135e'
down_revision = 'f0f0ca9029a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('employee', 'employee_is_admin')
    op.drop_column('employee', 'employee_is_manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_is_manager', sa.BOOLEAN(), nullable=False))
    op.add_column('employee', sa.Column('employee_is_admin', sa.BOOLEAN(), nullable=False))
    op.drop_column('employee', 'is_admin')
    # ### end Alembic commands ###
