"""Add tables and relationships

Revision ID: d67832b15175
Revises: cd6c195f4465
Create Date: 2022-04-11 16:51:56.569444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67832b15175'
down_revision = 'cd6c195f4465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_request',
    sa.Column('leave_request_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('approval_status_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.String(length=60), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_status_id'], ['approval_status.approval_status_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_type.leave_type_id'], ),
    sa.PrimaryKeyConstraint('leave_request_id')
    )
    op.create_index(op.f('ix_leave_request_created_date'), 'leave_request', ['created_date'], unique=False)
    op.create_index(op.f('ix_leave_request_deleted_date'), 'leave_request', ['deleted_date'], unique=False)
    op.create_index(op.f('ix_leave_request_updated_date'), 'leave_request', ['updated_date'], unique=False)
    op.create_table('manager',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('manager_id')
    )
    op.create_index(op.f('ix_manager_deleted_date'), 'manager', ['deleted_date'], unique=False)
    op.create_index(op.f('ix_manager_updated_date'), 'manager', ['updated_date'], unique=False)
    op.create_table('manager_employee',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.manager_id'], ),
    sa.PrimaryKeyConstraint('manager_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_employee')
    op.drop_index(op.f('ix_manager_updated_date'), table_name='manager')
    op.drop_index(op.f('ix_manager_deleted_date'), table_name='manager')
    op.drop_table('manager')
    op.drop_index(op.f('ix_leave_request_updated_date'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_deleted_date'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_created_date'), table_name='leave_request')
    op.drop_table('leave_request')
    # ### end Alembic commands ###
