"""change column names

Revision ID: f0f0ca9029a7
Revises: 8bc9bac39f3f
Create Date: 2022-04-26 12:26:40.597078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f0ca9029a7'
down_revision = '8bc9bac39f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_is_admin', sa.Boolean(), nullable=False))
    op.add_column('employee', sa.Column('employee_is_manager', sa.Boolean(), nullable=False))
    op.drop_column('employee', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    op.drop_column('employee', 'employee_is_manager')
    op.drop_column('employee', 'employee_is_admin')
    # ### end Alembic commands ###
